name: Deploy

on:
  push:
      branches:
        - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy files via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        KEY: ${{ secrets.SSH_RSA }}
      with:
        source: "."
        target: "/var/www/discord"

    - name: Restart Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        KEY: ${{ secrets.SSH_RSA }}
        script: systemctl restart NOVA_Laravel.service
